services:
  node1:
    build: { context: ., dockerfile: server/Dockerfile }
    container_name: av5-node1
    command: ["--id", "1"]
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    restart: unless-stopped
    networks:
      raft: { aliases: [node1-raft] }
      client: { aliases: [node1] }
    volumes: ["./data:/app/data"]
  node2:
    build: { context: ., dockerfile: server/Dockerfile }
    container_name: av5-node2
    command: ["--id", "2"]
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    restart: unless-stopped
    networks:
      raft: { aliases: [node2-raft] }
      client: { aliases: [node2] }
    volumes: ["./data:/app/data"]
  node3:
    build: { context: ., dockerfile: server/Dockerfile }
    container_name: av5-node3
    command: ["--id", "3"]
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    restart: unless-stopped
    networks:
      raft: { aliases: [node3-raft] }
      client: { aliases: [node3] }
    volumes: ["./data:/app/data"]
  node4:
    build: { context: ., dockerfile: server/Dockerfile }
    container_name: av5-node4
    command: ["--id", "4"]
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    restart: unless-stopped
    networks:
      raft: { aliases: [node4-raft] }
      client: { aliases: [node4] }
    volumes: ["./data:/app/data"]
  client:
    build: { context: ., dockerfile: client/Dockerfile }
    container_name: av5-client
    profiles: ["client"]
    networks: [client]
    # sem depends_on: evita que 'docker compose run client' reinicie nós parados (cenário 4)

networks:
  raft:
    driver: bridge
  client:
    driver: bridge
